name: upload my image to DockerHub

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create docker image
        run: echo Hello, world!

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/todo_project:latest

      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/todo_project:latest
